### ISSUE TITLE
Support for large models (llama) and models outside of transformer lens library

### ISSUE THREAD

**Issue by Maxipok** [montemac/activation_additions#6]
We are trying to test activation additions on larger models like llama-6b. We have streamlit working on the small transformer lens models (gpt-2 series). However, currently, we are unable to get llama to be loaded due to an issue with running the model on multiple GPU's and using transformer lens.

UPDATE: According to GPT-4, the problem is that the model is distributed across multiple GPUs, whereas the tensors are on a single GPU. In particular, in the model.generate function of the transformerlens library in the HookedTransformer folder puts the input tensor on a single device in the following line:

tokens = tokens.to(devices.get_device_for_block_index(0, self.cfg))

While this particular line might be easy to fix, according to GPT-4, fixing this issue would require enabling multi-GPU support across the transformerlens library. This seems like it would take a lot of time.

**Comment by DavidUdell** [comment]
I've been working on Uli's non-`TransformerLens` implementation of activation additions. That's currently in the `vicuna-13b` branch, `scripts/bigmodels.py`. It apparently works with vicuna-7B so far!

I'm working on (1) larger models and (2) the original quantitative metrics, to confirm that this is identical to the original `TransformerLens`-dependent implementation.

**Comment by DavidUdell** [comment]
With parallelization through `accelerate`, `vicuna-33B` is qualitatively working as well.

I'll turn to getting `LLaMA-65B` working here next, and confirming that everything's identical to the `TransformerLens` implementation with logprobs, but I think this is about done. Will close & pull request after getting quantitative confirmation!

**Comment by DavidUdell** [comment]
Confirmed a (qualitative) addition effect works on a local `LLaMA-65B`!

_However_, note that this reimplementation in `torch` _is not_ logit-for-logit identical to the original implementation—maybe because the original supports things like positional addition, padding, etc.
